# TODO: this should be added to the publish workflow
name: Create compat snapshot

on:
  workflow_dispatch:
  pull_request: # TEMP

jobs:
  compat-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Get latest existing tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: get-latest-tag

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Create compat snapshot
        run: cargo run -p c2pa-compat

      - name: Send compat PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Create compat snapshot for version ${{ steps.get-latest-tag.outputs.tag }}"
          labels: compat-snapshot # TODO: create label
          commit-message: "Create manifest compat snapshot"
          repository: contentauth/c2pa-fixtures
          branch: "compat-snapshot-${{ steps.get-latest-tag.outputs.tag }}"
          path: sdk/tests/fixtures
