# TODO: this should be added to the publish workflow
name: Create compat snapshot

on:
  workflow_dispatch:
  pull_request: # TEMP

jobs:
  compat-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest existing tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: get-latest-tag

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Create compat snapshot
        run: cargo run -p c2pa-compat

      - name: Get the latest tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      # - name: Send compat PR
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     title: "Create compat snapshot for ${{ env.LATEST_TAG }}"
      #     labels: compat-snapshot
      #     commit-message: "Create compat snapshot for ${{ env.LATEST_TAG }}"
      #     branch: "compat-snapshot-${{ env.LATEST_TAG }}"
      #     add-paths: sdk/tests/fixtures
      #     base: ${{ github.head_ref }}

      - name: TEMP---upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: sdk/tests/fixtures/compat/0.33.0
